NAME: FDD
DATASET:
  BATCH_SIZE: 32
  NUM_WORKERS: 16
  PPI: 500
  with_aug: true
  with_bg: true

MODEL:
  ndim_feat: 6
  input_norm: False
  middle_shape:
  - 512
  - 512
  tar_shape:
  - 256
  - 256